# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wle <- function(counts, act_thresh, spike_tol, spike_stop) {
    .Call(`_actigraph_sleepr_wle`, counts, act_thresh, spike_tol, spike_stop)
}

overlap <- function(start, end) {
    .Call(`_actigraph_sleepr_overlap`, start, end)
}

